engines:
  duplication:
    enabled: true
    exclude_paths:
      - test/
    config:
      languages:
        javascript:
          patterns:
            - src/**/*.js
  eslint:
    enabled: true
    channel: eslint-4

ratings:
  paths:
    - src/**/*.js
